#
###################################
# Site wide configuration
####################################
#
title: "Thomas Markovich"
email: thomasmarkovich@gmail.com
description: On Machine Learning, Python, C, and anything else
url: https://tmarkovich.github.io/ # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Boston/USA
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: "Thomas Markovich"
  avatar:
  job: "Machine Learning Research Scientist"
  bio: "A research scientist who loves to solve hard problems. Currently at Gamalon, Inc."
  email: thomasmarkovich@gmail.com
  disqus-shortname: tmarkovich
  twitter: tmarkovich #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: thomasmarkovich #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: thomas-markovich-75618044 #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
